#  Copyright (C) 2023, Advanced Micro Devices, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


activation_bitwidth:
- 2
- 2
- 2
- 3
- 4
- 5
batch_size: 512
epochs: 100
hidden_layer:
- 64
- 512
- 256
- 512
- 64
- 64
input_bitwidth: 4
input_fanin: 3
lr: 0.0019029804817149941
neuron_fanin:
- 3
- 4
- 4
- 3
- 3
- 2
output_bitwidth: 6
seed: 1016862180
warm_restart_freq: 87
wd: 0.009270086560698453
