#  Copyright (C) 2023, Advanced Micro Devices, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


activation_bitwidth:
- 4
- 5
- 3
- 6
- 2
batch_size: 512
epochs: 100
hidden_layer:
- 256
- 128
- 64
- 256
- 256
input_bitwidth: 4
input_fanin: 2
lr: 0.006065104971915896
neuron_fanin:
- 2
- 2
- 4
- 2
- 4
output_bitwidth: 5
seed: 1872119222
warm_restart_freq: 43
wd: 2.118117525975302e-05
