#  Copyright (C) 2023, Advanced Micro Devices, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


activation_bitwidth:
- 3
- 2
- 5
- 6
- 4
batch_size: 512
epochs: 100
hidden_layer:
- 128
- 128
- 512
- 64
- 128
input_bitwidth: 5
input_fanin: 3
lr: 4.7511600774683175e-05
neuron_fanin:
- 3
- 3
- 3
- 2
- 3
output_bitwidth: 6
seed: 377553323
warm_restart_freq: 67
wd: 0.0016494038404587733
