#  Copyright (C) 2023, Advanced Micro Devices, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


activation_bitwidth:
- 5
- 3
- 2
- 5
batch_size: 512
epochs: 100
hidden_layer:
- 256
- 64
- 128
- 256
input_bitwidth: 4
input_fanin: 3
lr: 0.02620568576649367
neuron_fanin:
- 3
- 2
- 3
- 3
output_bitwidth: 3
seed: 526421825
warm_restart_freq: 64
wd: 0.014949995909093019
